version: '3'
services:
  account-manager:
    build: ./account-manager
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=localhost
      - DB_USER=mrpuser
      - DB_PASSWORD=admin
      - DB_NAME=account_db
    depends_on:
      - db

  payment-manager:
    build: ./payment-manager
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=localhost
      - DB_USER=mrpuser
      - DB_PASSWORD=admin
      - DB_NAME=account_db
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: account_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
